export type CharacterAssetPack = {
  folder: string;
  base: any;
  all: readonly any[];
  poses: {
      base: any;
      bigGrin?: any;
      waving?: any;
      walking?: any;
    running?: any;
    jumping?: any;
    sitting?: any;
    celebration?: any;
    thinking?: any;
    brushing?: any;
    reading?: any;
    cooking?: any;
    sleeping?: any;
    resting?: any;
  };
};

export const characterAssets = {
  aidin: {
    folder: 'assets/neli-world/characters/Aidin',
    base: require('../../assets/neli-world/characters/Aidin/01_owl_base_standing.png'),
    all: [
      require('../../assets/neli-world/characters/Aidin/01_owl_base_standing.png'),
      require('../../assets/neli-world/characters/Aidin/02_owl_waving.png'),
      require('../../assets/neli-world/characters/Aidin/03_owl_walking.png'),
      require('../../assets/neli-world/characters/Aidin/04_owl_running.png'),
      require('../../assets/neli-world/characters/Aidin/05_owl_jumping.png'),
      require('../../assets/neli-world/characters/Aidin/06_owl_sitting_floor.png'),
      require('../../assets/neli-world/characters/Aidin/07_owl_celebration.png'),
      require('../../assets/neli-world/characters/Aidin/08_owl_thinking.png'),
      require('../../assets/neli-world/characters/Aidin/09_owl_big_teeth_brushing_confirmed.png'),
      require('../../assets/neli-world/characters/Aidin/09_owl_big_teeth_brushing_smile.png'),
      require('../../assets/neli-world/characters/Aidin/10_owl_reading_book.png'),
      require('../../assets/neli-world/characters/Aidin/11_owl_cooking.png'),
      require('../../assets/neli-world/characters/Aidin/12_owl_sleeping_front.png'),
      require('../../assets/neli-world/characters/Aidin/13_owl_sleeping_side.png'),
    ],
    poses: {
      base: require('../../assets/neli-world/characters/Aidin/01_owl_base_standing.png'),
      waving: require('../../assets/neli-world/characters/Aidin/02_owl_waving.png'),
      walking: require('../../assets/neli-world/characters/Aidin/03_owl_walking.png'),
      running: require('../../assets/neli-world/characters/Aidin/04_owl_running.png'),
      jumping: require('../../assets/neli-world/characters/Aidin/05_owl_jumping.png'),
      sitting: require('../../assets/neli-world/characters/Aidin/06_owl_sitting_floor.png'),
      celebration: require('../../assets/neli-world/characters/Aidin/07_owl_celebration.png'),
      thinking: require('../../assets/neli-world/characters/Aidin/08_owl_thinking.png'),
      brushing: require('../../assets/neli-world/characters/Aidin/09_owl_big_teeth_brushing_smile.png'),
      reading: require('../../assets/neli-world/characters/Aidin/10_owl_reading_book.png'),
      cooking: require('../../assets/neli-world/characters/Aidin/11_owl_cooking.png'),
      sleeping: require('../../assets/neli-world/characters/Aidin/12_owl_sleeping_front.png'),
    },
  },
  dara: {
    folder: 'assets/neli-world/characters/Dara',
    base: require('../../assets/neli-world/characters/Dara/cheerful_cartoon_giraffe_character.png'),
    all: [
      require('../../assets/neli-world/characters/Dara/cheerful_baby_giraffe_in_motion.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_baby_giraffe_plush_mascot.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_baby_giraffe_with_a_skirt.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_cartoon_giraffe_character.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_cartoon_giraffe_character_design.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_cartoon_giraffe_character_walking.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_cartoon_giraffe_in_motion.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_chibi_giraffe_in_motion.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_dancing_giraffe_character.png'),
      require('../../assets/neli-world/characters/Dara/cheerful_giraffe_on_the_move.png'),
      require('../../assets/neli-world/characters/Dara/happy_baby_giraffe_in_cheerful_pose.png'),
      require('../../assets/neli-world/characters/Dara/happy_baby_giraffe_with_a_big_grin.png'),
      require('../../assets/neli-world/characters/Dara/happy_giraffe_chef_with_bowl_and_spoon.png'),
      require('../../assets/neli-world/characters/Dara/happy_giraffe_reading_a_book.png'),
      require('../../assets/neli-world/characters/Dara/happy_jumping_giraffe_mascot_character.png'),
      require('../../assets/neli-world/characters/Dara/sleeping_giraffe_under_blue_blanket.png'),
      require('../../assets/neli-world/characters/Dara/sleepy_giraffe_in_a_cozy_bed.png'),
    ],
    poses: {
      base: require('../../assets/neli-world/characters/Dara/cheerful_cartoon_giraffe_character.png'),
      bigGrin: require('../../assets/neli-world/characters/Dara/happy_baby_giraffe_with_a_big_grin.png'),
      waving: require('../../assets/neli-world/characters/Dara/happy_jumping_giraffe_mascot_character.png'),
      walking: require('../../assets/neli-world/characters/Dara/cheerful_cartoon_giraffe_character_walking.png'),
      running: require('../../assets/neli-world/characters/Dara/cheerful_giraffe_on_the_move.png'),
      jumping: require('../../assets/neli-world/characters/Dara/happy_jumping_giraffe_mascot_character.png'),
      sitting: require('../../assets/neli-world/characters/Dara/cheerful_baby_giraffe_plush_mascot.png'),
      celebration: require('../../assets/neli-world/characters/Dara/cheerful_dancing_giraffe_character.png'),
      thinking: require('../../assets/neli-world/characters/Dara/happy_giraffe_reading_a_book.png'),
      brushing: require('../../assets/neli-world/characters/Dara/happy_baby_giraffe_in_cheerful_pose.png'),
      reading: require('../../assets/neli-world/characters/Dara/happy_giraffe_reading_a_book.png'),
      cooking: require('../../assets/neli-world/characters/Dara/happy_giraffe_chef_with_bowl_and_spoon.png'),
      sleeping: require('../../assets/neli-world/characters/Dara/sleepy_giraffe_in_a_cozy_bed.png'),
    },
  },
    lila: {
      folder: 'assets/neli-world/characters/Lila',
      base: require('../../assets/neli-world/characters/Lila/happy_lamb_in_yellow_overalls.png'),
      all: [
        require('../../assets/neli-world/characters/Lila/cheerful_baby_lamb_in_yellow_overalls.png'),
        require('../../assets/neli-world/characters/Lila/cheerful_lamb_baker_with_a_spoon.png'),
        require('../../assets/neli-world/characters/Lila/cheerful_lamb_waving_in_yellow_overalls.png'),
        require('../../assets/neli-world/characters/Lila/lila_big_smile.png'),
        require('../../assets/neli-world/characters/Lila/lila_cooking.png'),
        require('../../assets/neli-world/characters/Lila/lila_jumping.png'),
        require('../../assets/neli-world/characters/Lila/lila_reading.png'),
        require('../../assets/neli-world/characters/Lila/lila_running.png'),
        require('../../assets/neli-world/characters/Lila/lila_sitting.png'),
        require('../../assets/neli-world/characters/Lila/lila_sleeping.png'),
        require('../../assets/neli-world/characters/Lila/lila_standing.png'),
        require('../../assets/neli-world/characters/Lila/lila_thinking.png'),
        require('../../assets/neli-world/characters/Lila/lila_waving.png'),
        require('../../assets/neli-world/characters/Lila/lamb_big_teeth.png'),
        require('../../assets/neli-world/characters/Lila/cute_lamb_reading_a_book.png'),
        require('../../assets/neli-world/characters/Lila/happy_baby_lamb_in_yellow_overalls.png'),
        require('../../assets/neli-world/characters/Lila/happy_lamb_in_yellow_overalls.png'),
        require('../../assets/neli-world/characters/Lila/happy_lamb_on_the_move.png'),
      require('../../assets/neli-world/characters/Lila/peaceful_sleeping_lamb_in_a_cozy_bed.png'),
      require('../../assets/neli-world/characters/Lila/sleeping_lamb_in_cozy_bed.png'),
      require('../../assets/neli-world/characters/Lila/lamb_big_teeth.png'),
    ],
      poses: {
        base: require('../../assets/neli-world/characters/Lila/happy_lamb_in_yellow_overalls.png'),
        bigSmile: require('../../assets/neli-world/characters/Lila/lila_big_smile.png'),
        cookingAlt: require('../../assets/neli-world/characters/Lila/lila_cooking.png'),
        jumpingAlt: require('../../assets/neli-world/characters/Lila/lila_jumping.png'),
        readingAlt: require('../../assets/neli-world/characters/Lila/lila_reading.png'),
        runningAlt: require('../../assets/neli-world/characters/Lila/lila_running.png'),
        sittingAlt: require('../../assets/neli-world/characters/Lila/lila_sitting.png'),
        sleepingAlt: require('../../assets/neli-world/characters/Lila/lila_sleeping.png'),
        standing: require('../../assets/neli-world/characters/Lila/lila_standing.png'),
        thinkingAlt: require('../../assets/neli-world/characters/Lila/lila_thinking.png'),
        wavingAlt: require('../../assets/neli-world/characters/Lila/lila_waving.png'),
        waving: require('../../assets/neli-world/characters/Lila/cheerful_lamb_waving_in_yellow_overalls.png'),
        walking: require('../../assets/neli-world/characters/Lila/happy_lamb_on_the_move.png'),
        running: require('../../assets/neli-world/characters/Lila/happy_lamb_on_the_move.png'),
        jumping: require('../../assets/neli-world/characters/Lila/lamb_big_teeth.png'),
        sitting: require('../../assets/neli-world/characters/Lila/cheerful_baby_lamb_in_yellow_overalls.png'),
      celebration: require('../../assets/neli-world/characters/Lila/cheerful_lamb_baker_with_a_spoon.png'),
      thinking: require('../../assets/neli-world/characters/Lila/cute_lamb_reading_a_book.png'),
      reading: require('../../assets/neli-world/characters/Lila/cute_lamb_reading_a_book.png'),
      cooking: require('../../assets/neli-world/characters/Lila/cheerful_lamb_baker_with_a_spoon.png'),
      sleeping: require('../../assets/neli-world/characters/Lila/sleeping_lamb_in_cozy_bed.png'),
      brushing: require('../../assets/neli-world/characters/Lila/lamb_big_teeth.png'),
    },
  },
  mila: {
    folder: 'assets/neli-world/characters/Mila',
    base: require('../../assets/neli-world/characters/Mila/cheerful_kawaii_bunny_character.png'),
    all: [
      require('../../assets/neli-world/characters/Mila/bunny_reading_a_book_sprite.png'),
      require('../../assets/neli-world/characters/Mila/cheerful_bunny_chef_with_cooking_tools.png'),
      require('../../assets/neli-world/characters/Mila/cheerful_bunny_waving_in_style.png'),
      require('../../assets/neli-world/characters/Mila/cheerful_kawaii_bunny_character.png'),
      require('../../assets/neli-world/characters/Mila/curious_bunny_in_thought.png'),
      require('../../assets/neli-world/characters/Mila/excited_bunny_in_vibrant_jump.png'),
      require('../../assets/neli-world/characters/Mila/happy_bunny_in_motion.png'),
      require('../../assets/neli-world/characters/Mila/mila_brush.png'),
      require('../../assets/neli-world/characters/Mila/mila_teeth.png'),
      require('../../assets/neli-world/characters/Mila/peaceful_bunny_napping_in_bed.png'),
    ],
    poses: {
      base: require('../../assets/neli-world/characters/Mila/cheerful_kawaii_bunny_character.png'),
      waving: require('../../assets/neli-world/characters/Mila/cheerful_bunny_waving_in_style.png'),
      walking: require('../../assets/neli-world/characters/Mila/happy_bunny_in_motion.png'),
      running: require('../../assets/neli-world/characters/Mila/happy_bunny_in_motion.png'),
      jumping: require('../../assets/neli-world/characters/Mila/excited_bunny_in_vibrant_jump.png'),
      sitting: require('../../assets/neli-world/characters/Mila/curious_bunny_in_thought.png'),
      celebration: require('../../assets/neli-world/characters/Mila/cheerful_bunny_chef_with_cooking_tools.png'),
      thinking: require('../../assets/neli-world/characters/Mila/curious_bunny_in_thought.png'),
      brushing: require('../../assets/neli-world/characters/Mila/mila_brush.png'),
      reading: require('../../assets/neli-world/characters/Mila/bunny_reading_a_book_sprite.png'),
      cooking: require('../../assets/neli-world/characters/Mila/cheerful_bunny_chef_with_cooking_tools.png'),
      sleeping: require('../../assets/neli-world/characters/Mila/peaceful_bunny_napping_in_bed.png'),
    },
  },
  neli: {
    folder: 'assets/neli-world/characters/Neli',
    base: require('../../assets/neli-world/characters/Neli/01_nelly_base.png'),
    all: [
      require('../../assets/neli-world/characters/Neli/01_nelly_base.png'),
      require('../../assets/neli-world/characters/Neli/01_nelly_base1.png'),
      require('../../assets/neli-world/characters/Neli/01_base_standing.png'),
      require('../../assets/neli-world/characters/Neli/02_nelly_big_teeth_brushing.png'),
      require('../../assets/neli-world/characters/Neli/02_nelly_wave.png'),
      require('../../assets/neli-world/characters/Neli/03_nelly_walk.png'),
      require('../../assets/neli-world/characters/Neli/04_nelly_run_front.png'),
      require('../../assets/neli-world/characters/Neli/05_nelly_run_side.png'),
      require('../../assets/neli-world/characters/Neli/06_nelly_jump.png'),
      require('../../assets/neli-world/characters/Neli/07_nelly_dance.png'),
      require('../../assets/neli-world/characters/Neli/08_nelly_excited.png'),
      require('../../assets/neli-world/characters/Neli/09_nelly_sitting_floor.png'),
      require('../../assets/neli-world/characters/Neli/10_excited.png'),
      require('../../assets/neli-world/characters/Neli/11_sitting_floor.png'),
      require('../../assets/neli-world/characters/Neli/12_sleep_left_no_bed.png'),
      require('../../assets/neli-world/characters/Neli/13_sleep_right_no_bed.png'),
      require('../../assets/neli-world/characters/Neli/14_sleep_blanket_pillow_left.png'),
      require('../../assets/neli-world/characters/Neli/15_sleep_blanket_pillow_right.png'),
      require('../../assets/neli-world/characters/Neli/17_cooking.png'),
      require('../../assets/neli-world/characters/Neli/18_reading_book.png'),
    ],
    poses: {
      base: require('../../assets/neli-world/characters/Neli/01_nelly_base.png'),
      waving: require('../../assets/neli-world/characters/Neli/02_nelly_wave.png'),
      walking: require('../../assets/neli-world/characters/Neli/03_nelly_walk.png'),
      running: require('../../assets/neli-world/characters/Neli/04_nelly_run_front.png'),
      jumping: require('../../assets/neli-world/characters/Neli/06_nelly_jump.png'),
      sitting: require('../../assets/neli-world/characters/Neli/09_nelly_sitting_floor.png'),
      celebration: require('../../assets/neli-world/characters/Neli/07_nelly_dance.png'),
      thinking: require('../../assets/neli-world/characters/Neli/08_nelly_excited.png'),
      brushing: require('../../assets/neli-world/characters/Neli/02_nelly_big_teeth_brushing.png'),
      reading: require('../../assets/neli-world/characters/Neli/18_reading_book.png'),
      cooking: require('../../assets/neli-world/characters/Neli/17_cooking.png'),
      sleeping: require('../../assets/neli-world/characters/Neli/12_sleep_left_no_bed.png'),
      resting: require('../../assets/neli-world/characters/Neli/09_nelly_sitting_floor.png'),
    },
  },
} as const;
